# Dependencies
markdown:         redcarpet 
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Just Another Programming Blog
tagline:          'Rashid Khan'
description:      'Just Another Programming Blog by Rashid Khan'
url:              http://rashoodkhan.github.io

author:
  name:           'Rashid Khan'
  url:            https://twitter.com/WorkaholicKhan

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/rashoodkhan/rashoodkhan.github.io
